common:
  height: 480
  width: 640
  exp_name: evimo2
  checkpoint: weights/ETAP_v1_cvpr25.pth

model:
  num_in_channels: 10
  stride: 4
  window_len: 8
  num_virtual_tracks: 64

data:
  data_root: data/evimo2
  dataset_name: evimo2
  preprocessed_name: event_stack_v1
  metadata_path: config/misc/evimo2/val_samples.csv